name: Deploy to Kubernetes prod env

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install envsubst
      run: sudo apt-get install -y gettext

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v2
      with:
        version: '1.29.2'

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Deploy to Test Environment
      run: |
        helm upgrade --install my-app ./my-app \
          --namespace test \
          --values ./my-app/values-test-temp.yaml
